### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by SourDiesel** [j26design/Ecwid-Premium#22]
Not sure what the changes are. Can't change the color of the top navigation bar, only the font color. No menu or submenu height control? The menu only has left or right alignment with no centered  alignment? The submenu has no standardized size or ability to change the space between the line items in the sub navigation? Sorry, if anything, this update is worse and none of the problems seem to be solved.  The whole thing is really confusing in comparison what you had before...

![safariscreensnapz014](https://cloud.githubusercontent.com/assets/20111755/16878035/8d82a598-4a70-11e6-91c5-8266e26c918a.jpg)

**Comment by jp26jp** [comment]
**Can't change the color of the top navigation bar**
Yes you can:
<img width="332" alt="screenshot 2016-07-15 08 50 18" src="https://cloud.githubusercontent.com/assets/18344950/16878301/441c7a8e-4a69-11e6-9865-b7450b1afa78.png">

**No menu or submenu height control**
The height is controlled by the height of the widget. If the widget is set to 50px tall, then the menu and submenu items are 50px tall.

**The menu only has left or right alignment with no centered alignment?**
Yes, because of the way Ecwid designed their menu, it made it way too unstable (for example, the original issue you reported) to do anything other than left or right alignment.

**If anything, this update is worse and none of the problems seem to be solved.**
If you have anything constructive to add or would like to request a specific feature, let me know. If not, you are always welcome to use [the stock version](https://support.ecwid.com/hc/en-us/articles/207359839-Horizontal-Categories) of the navigation widget.

**Comment by SourDiesel** [comment]
John - I apologize for my frustration, but you set an expectation in your demo for the navigation, that's why I bought it. Don't get me wrong, I love what your doing... 

 The menu bar does not change color. I tried multiple different options and none work.

![adobe muse ccscreensnapz001](https://cloud.githubusercontent.com/assets/20111755/16879667/341b11c8-4a77-11e6-9a6f-b1f0bb63ab30.jpg)
![adobe muse ccscreensnapz002](https://cloud.githubusercontent.com/assets/20111755/16879669/3469c642-4a77-11e6-9736-021d19412f06.jpg)
![adobe muse ccscreensnapz003](https://cloud.githubusercontent.com/assets/20111755/16879668/345bb2dc-4a77-11e6-828f-971bb7f7d951.jpg)

**Comment by jp26jp** [comment]
The screenshot you're sending me is for the color, not the background. If you want to edit the background, you have to use the settings under the background. If you can't see the settings, collapse the panel, reopen the panel, then use the scrollbar to manually scroll down the widget.

**Comment by SourDiesel** [comment]
That did the trick John. Thanks again...

**Comment by jp26jp** [comment]
Of course. Let me know if there's anything that this widget is missing that the other had. I will add a separate setting for adjusting the height of the submenu's so that they're not copying the top-level menu.
