### ISSUE TITLE
Storefront Update 7-14-2016

### ISSUE THREAD

**Issue by h2oonstone** [j26design/Ecwid-Premium#24]
I tried to update my site with the new storefront last night and it crashed Muse. I reinstalled my backup files and retried the update again just now - and it crashed again.

**Comment by jp26jp** [comment]
Thats strange. Windows or Mac?

**Comment by jp26jp** [comment]
Have you mentioned it to [Muse](http://museprerelease.com)?

**Comment by h2oonstone** [comment]
Mac

**Comment by h2oonstone** [comment]
No... but, I probably sent the crash report.

I suspect they will tell me it is a bug the widget - which is what it seems. I was able to go back and use the earlier version before this update just fine.

**Comment by jp26jp** [comment]
Maybe, but [my store](https://www.j-26.com/store/) and 2 [demo stores](https://www.j-26.com/ecommerce/ecwid/ecwid-premium/demo/light-layout.html) I made use the latest version of every widget. I'd mention it to [Muse](http://museprerelease.com/) because no one has reported this issue. Feel free to tag me (John Perry) in the post. They're usually really good at finding these kinds of bugs. 

I'm sure that there is a conflict, but the bug is on Muse's side, otherwise the widget wouldn't work for me either.

**Comment by h2oonstone** [comment]
John - the only thing I did was add the new version of the All Storefront Widgets and on upload it crashed. I restored my site with the old version of the storefront widget was able to upload it fine. Just to make sure it wasn’t user error I tried the new version of the storefront widget again - and Muse crashed on upload again. And, again I restored it to the previous version and it uploaded fine.
I am not following how that could be a Muse bug.

**Comment by jp26jp** [comment]
Because like I just said:

1. The widget wouldn't work for me if it was a bug in the widget.
2. There would have been reports of other users not being able to use the widget.

More importantly, a bug in the widget cannot cause Muse to crash. Even if the widget makes Muse crash, it's still a bug in Muse. Muse developers made it so that nothing within a MuCow (the extension that widgets are built in) can be placed on a page if the MuCow's markup is invalid. Once it's placed on a page, the widget only affects the markup of the exported site. This means that a bug in the widget can only show up in the form of messing up your published site. A bug in Muse shows up in the form of Muse crashing.

If you'd like to upload the Muse file, I'm [happy to take a look](https://www.dropbox.com/request/jTLS8SM5TU547RCjpgRN)

**Comment by h2oonstone** [comment]
Thanks for taking a look John - uploading the muse file now

**Comment by jp26jp** [comment]
I updated the widgets, exported the site, and Muse didn't crash. So whatever is going on has to do with a conflict with your install of Muse. If you contact [Muse](http://museprerelease.com/) they might be able to identify what is going on.

**Comment by h2oonstone** [comment]
Thanks for checking

**Comment by h2oonstone** [comment]
Hi John -
I tried again after uninstalling and reinstalling Muse and it crashed on upload. - So I tried exporting the file to my desktop and uploading to the server from there and that worked. Went back to my Muse file and updated directly to server from Muse and it is uploading without crashing. Yep, sounds like a Muse bug. Ann

**Comment by jp26jp** [comment]
Oh weird! I'm glad you got it figured out though!
