### ISSUE TITLE
Cart counter V1.36 issue

### ISSUE THREAD

**Issue by jp26jp** [j26design/Ecwid-Premium#64]

**Comment by jp26jp** [comment]
I doubt this is a cart counter issue since I'm using the latest version of the cart counter on [my own site](https://www.j-26.com/store/). However, [please upload your file here so I can take a look](https://www.dropbox.com/request/jTLS8SM5TU547RCjpgRN).

**Comment by HDRSky360** [comment]
Thank for your reply. 
There are 2 issues actualy. 
The first one is solved and was due to GeoTrust Metadata for display SSL certification icon.
I removed it, and now, Cart counter basicly works again but not in all cases. I
Indeed that works only with some Ecwid IDs.
I sent you a virgin project with 2 different ones on your Dropbox link.

Thank you

**Comment by jp26jp** [comment]
It's not possible for it to only work with some Ecwid IDs. If it works with any Ecwid ID, it works with all. The only reason why it wouldn't work with one and not the other is because you're using multiple Ecwid IDs which is what you're doing in the example that you uploaded. Your Ecwid IDs need to be consistent.

**Comment by HDRSky360** [comment]
OK. Exept that if I create a new virgin muse project, with nothing inside setting apart a unique cart counter, with this ID (9042815), it doesn't work at all. There wasn't any issue when I created my website 2 weeks ago, but this ID doesn't work anymore, even on a freshly created project. This is very strange, because the online website work perfectly, but I can't modifiy it anymore on muse.
